### ISSUE TITLE
Linux Mint 17

### ISSUE THREAD

**Issue by akamizi** [bharadwaj-raju/WeatherDesk#12]
python3 WeatherDesk.py --help

Traceback (most recent call last):
  File "WeatherDesk.py", line 14, in <module>
    import Desktop
  File "/home/mizi/Programmi/WeatherDesk/Desktop.py", line 157
    old_working_dir = os.getcwd()
    ^
IndentationError: unexpected indent

**Comment by bharadwaj-raju** [comment]
Fixed by commit [41fc2b7](https://github.com/bharadwaj-raju/WeatherDesk/commit/41fc2b7b05b04aaf4e427a24f286b54e0ccc4df9).
