### ISSUE TITLE
cant run script

### ISSUE THREAD

**Issue by dsdmsa** [bharadwaj-raju/WeatherDesk#24]
sudo python3 WeatherDesk.py --city chisinau
[City checking] No error.
mostly clear
Chisinau Chisinau
/home/myname/.weatherdesk_walls/normal.jpg
Traceback (most recent call last):
  File "WeatherDesk.py", line 379, in <module>
    os.path.join(walls_dir, get_file_name(weather, time=use_time)))
  File "/home/myname/Desktop/WeatherDesk-master/Desktop.py", line 104, in set_wallpaper
    desktop_env = get_desktop_environment()
  File "/home/myname/Desktop/WeatherDesk-master/Desktop.py", line 79, in get_desktop_environment
    elif is_running('xfce-mcs-manage'): return 'xfce4'
  File "/home/myname/Desktop/WeatherDesk-master/Desktop.py", line 96, in is_running
    if re.search(process, x):
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "WeatherDesk.py", line 399, in <module>
    print(trace_main_loop)
NameError: name 'trace_main_loop' is not defined

**Comment by bharadwaj-raju** [comment]
Why `sudo`?

**Comment by bharadwaj-raju** [comment]
Fixed with commit [3d45866](https://github.com/bharadwaj-raju/WeatherDesk/commit/3d4586657f0f356ecc11ea5e68c414f9c0058966).

Again, there is no need for `sudo`, please do not run script with it.
