### ISSUE TITLE
Error on Linux Xfce4

### ISSUE THREAD

**Issue by kasperkopf** [bharadwaj-raju/WeatherDesk#31]
I got an error while using your script in my Xfce4 desktop environment. See below:
```
[Main loop] 
Traceback (most recent call last):
  File "WeatherDesk.py", line 419, in <module>
    main()
  File "WeatherDesk.py", line 406, in main
    os.path.join(walls_dir, get_file_name(weather, time=use_time)))
  File "/home/xek6ae/WeatherDesk/Desktop.py", line 203, in set_wallpaper
    for i in list_of_properties.subprocesslit('\n'):
AttributeError: 'str' object has no attribute 'subprocesslist'
```
I change the line 203 of Dektop.py `for i in list_of_properties.split('\n'):` an then the script works fine for me.

**Comment by bharadwaj-raju** [comment]
Fixed by your PR #32
