### ISSUE TITLE
Gives error on invalid city (SSL error?)

### ISSUE THREAD

**Issue by Yerlix** [bharadwaj-raju/WeatherDesk#36]
Hi

I've just downloaded this repository to give it a test run.
But when executing the WeatherDesk.py script, I get the following error:

![image](https://user-images.githubusercontent.com/3891388/29927777-9cd43e3a-8e67-11e7-813b-68f6ad18a468.png)

I'm not a python dev so I'm not able to figure out what's wrong here.
Any help is welcome!

**Comment by bharadwaj-raju** [comment]
Yes, an SSL error. Can you try visiting http://ipinfo.io/json in your browser?

**Comment by Yerlix** [comment]
I can see the correct JSON information:
<img width="270" alt="screen shot 2017-09-01 at 07 26 55" src="https://user-images.githubusercontent.com/3891388/29956416-2f3b2124-8ee7-11e7-985d-5b3b328a1e8c.png">

**Comment by bharadwaj-raju** [comment]
Try running these two commands:

    $ curl ipinfo.io/json

    $ python3 -c "from urllib.request import urlopen; print(urlopen('http://ipinfo.io/json').read().decode('utf-8'))"

Both show correct for me.

**Comment by Yerlix** [comment]
Both commands seem correct to me as well.
I get JSON back with my location data.

**Comment by bharadwaj-raju** [comment]
Ah, the error is on a Yahoo! API query: 

https://query.yahooapis.com/v1/public/yql?q=select%20%2A%20from%20geo.places(5)%20where%20text%3D"' + city + r'"&format=json'

Replace " + city + " with your city name.

**Comment by Yerlix** [comment]
I've tried changing it to this:
https://query.yahooapis.com/v1/public/yql?q=select%20%2A%20from%20geo.places(5)%20where%20text%3DAntwerp&format=json

But that gives the same error

**Comment by bharadwaj-raju** [comment]
In the browser?

**Comment by Yerlix** [comment]
I get this:
![image](https://user-images.githubusercontent.com/3891388/30003258-c79fc3b4-90ba-11e7-9868-269082189436.png)
I've also tried changing the city "Antwerp" to my IP address from ipinfo.io, which results in:
![image](https://user-images.githubusercontent.com/3891388/30003270-f7b4ea52-90ba-11e7-8466-02ff58e89a1b.png)

**Comment by bharadwaj-raju** [comment]
Looks like Yahoo! changed their *public*, supposedly "stable" API. Actually, I might as well remove this part from the code altogether, as it serves no purpose except to see if it is a "valid city".

**Comment by Yerlix** [comment]
Alright. Let me know when you've changed the code. I'll test it again then.

**Comment by bharadwaj-raju** [comment]
Hopefully fixed by 62e059cc4efd.

**Comment by Yerlix** [comment]
Now I get this error when using the command
` …/WeatherDesk-master  python3 WeatherDesk.py --city="Antwerp"                              1 ↵  12114  15:31:44
[Main loop]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "WeatherDesk.py", line 375, in <module>
    main()
  File "WeatherDesk.py", line 350, in main
    weather_json = json.loads(urlopen(weather_json_url).read().decode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>`

**Comment by Yerlix** [comment]
Just tried it again today on another laptop (changed laptops).
This seems working correctly now, only my second desktop (MacBook Pro) hasn't changed. My second screen however did.

**Comment by bharadwaj-raju** [comment]
Then it seems like a problem with the previous system...

Also, if I read that correctly, it is a multi-screen issue? Can you please open a new issue for that?

**Comment by Yerlix** [comment]
It looks like the previous laptop's fault indeed.
I'm using it on OSX so I think it would be the same as https://github.com/bharadwaj-raju/WeatherDesk/issues/34
