### ISSUE TITLE
UnicodeEncodeError if your city have non ascii character

### ISSUE THREAD

**Issue by acantepie** [bharadwaj-raju/WeatherDesk#39]
Hello,

Thx for python script :)

I am currently in Saint-lô, and your script fail because i have non ascii character in my city.
```
[Main loop] 
Traceback (most recent call last):
  File "WeatherDesk.py", line 377, in <module>
    main()
  File "WeatherDesk.py", line 350, in main
    print(urlopen(weather_json_url))
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1250, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.6/http/client.py", line 1117, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xf4' in position 147: ordinal not in range(128)
```

I have fixed WeatherDesk.py by importing urllib.parse.
```
...
import urllib.parse
...

def main():
	weather_json_url = r'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22' + urllib.parse.quote(city) + '%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys'
	weather_json = json.loads(urlopen(weather_json_url).read().decode('utf-8'))
```

**Comment by bharadwaj-raju** [comment]
Thanks! Fixed now with your solution.
